version: "3"

networks:
  lbs.net:
    driver: bridge

services:
  api.reviews:
    image: damou/php:8-apache-mysql-composer-nano-a2enmod-public
    ports:
      - "8080:80"
      - "10443:443"
    volumes:
      - ./:/var/www/html/TD2
    working_dir: /var/www/html/TD2
    networks:
      - lbs.net
    links:
      - mongo.cat:dbcat

  mongo.cat:
    image: mongo:latest
    working_dir: /var/data/
    ports:
      - "27018:27017"
    networks:
      - lbs.net
    volumes:
      - ./resources/seeds:/var/data