version: "3"

networks:
  lbs.net:
    driver: bridge

services:
  prism.app:
    image: damou/php:8-apache-mysql-composer-nano-a2enmod
    ports:
      - "8080:80"
      - "10443:443"
    volumes:
      - ./:/var/www/html/TD2
    working_dir: /var/www/html/TD2
    networks:
      - lbs.net
    links:
      - mysql.commande:commande

  mysql.commande:
    image: damou/mysql:TD2-ORM-UPDATE
    environment:
      MYSQL_USER: dede
      MYSQL_PASSWORD: dede
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - lbs.net
    volumes:
      - ./config:/mnt/