name: Test

on:
  push:
    branches:
      - test

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php- 

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        run: composer run-script test-php

      - name: Set environment variables
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV

      - name: environment_variables
        run: echo "::set-output name=GITHUB_SHA_SHORT::$(echo $GITHUB_SHA_SHORT)"
        id: AWS

      - name: phpunit error tests messages
        run: echo "::set-output name=msg::$(composer run-script test-php | grep 'php:' |  head -4 | tail -1 | cut -d' ' -f2-)"
        id: phpunit_test_error

      - name: phpunit error tests messages
        run: echo "::set-output name=msg::$(composer run-script test-php |  grep '1)' |  head -4 | tail -1 | cut -d' ' -f2-)"
        id: phpunit_test_error_short

      - uses: actions/checkout@v2
      - name: Create an issue
        if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          actor: ${{ github.actor }}
          test: duplicate
          sha: ${{ steps.AWS.outputs.GITHUB_SHA_SHORT }}
          error: ${{ steps.phpunit_test_error.outputs.msg }}
          error_short: ${{ steps.phpunit_test_error_short.outputs.msg }}
        with:
          assignees: ${{ github.actor }}
          update_existing: true
          search_existing: open

      - name: pull-request
        if: ${{ success() }}
        uses: repo-sync/pull-request@v2
        env:
          GITHUB_TOKEN: ${{ secrets.MyWorkflow2  }}
        with:
          GITHUB_TOKEN: ${{ secrets.MyWorkflow2  }}
          source_branch: "test"
          destination_branch: "main"
          pr_title: ${{ github.event.head_commit.message }}
          pr_body: ${{ github.event.commits.message }}
          pr_assignee: "damouu"